import os
import time
import subprocess
import requests


PIXAZO_API_KEY = os.getenv("PIXAZO_API_KEY")

GENERATE_URL = (
    "https://gateway.pixazo.ai/"
    "ltx-video/v1/image-to-video"
)

STATUS_URL = (
    "https://gateway.pixazo.ai/"
    "v2/requests/status"
)


def animate_image(
    image_url,
    motion_prompt,
    output_file
):
    """
    Convert a still image into a real AI-generated
    animated video using Pixazo LTX Video.
    """

    if not PIXAZO_API_KEY:
        raise ValueError(
            "PIXAZO_API_KEY is not set."
        )

    if not image_url:
        raise ValueError(
            "Image URL is empty."
        )

    if not motion_prompt:
        raise ValueError(
            "Motion prompt is empty."
        )

    headers = {
        "Content-Type": "application/json",
        "Cache-Control": "no-cache",
        "Ocp-Apim-Subscription-Key": PIXAZO_API_KEY,
    }

    data = {
        "prompt": motion_prompt,

        # Public HTTPS image generated by Pixazo
        "image_url": image_url,

        # Keep the generated video closely tied
        # to the source image.
        "strength": 1.0,

        # Vertical 9:16 YouTube Shorts format.
        "width": 576,
        "height": 1024,

        # About 5 seconds at 24 FPS.
        "num_frames": 121,
        "frame_rate": 24,

        # Keep the current working settings.
        "steps": 8,
        "cfg": 3.0,
    }

    print()
    print("=" * 60)
    print("🎬 STARTING AI ANIMATION")
    print("=" * 60)

    print("📐 Output: 576x1024 (9:16)")
    print("🎞️ Frames: 121")
    print("🎥 FPS: 24")
    print("⏱️ Duration: about 5 seconds")

    print()
    print("Motion prompt:")
    print(motion_prompt)

    try:

        response = requests.post(
            GENERATE_URL,
            headers=headers,
            json=data,
            timeout=120,
        )

        response.raise_for_status()

    except requests.exceptions.RequestException as error:

        raise RuntimeError(
            f"Pixazo LTX request failed: {error}"
        ) from error

    try:

        result = response.json()

    except ValueError as error:

        raise RuntimeError(
            "Pixazo returned invalid JSON."
        ) from error

    print()
    print("Pixazo response:")
    print(result)

    request_id = result.get(
        "request_id"
    )

    if not request_id:

        raise RuntimeError(
            "Pixazo did not return a request_id: "
            f"{result}"
        )

    print()
    print(
        "🆔 Animation request created:",
        request_id
    )

    # --------------------------------------------------
    # WAIT FOR VIDEO GENERATION
    # --------------------------------------------------

    max_polls = 120

    for poll_number in range(
        1,
        max_polls + 1
    ):

        time.sleep(5)

        try:

            status_response = requests.get(
                f"{STATUS_URL}/{request_id}",
                headers={
                    "Ocp-Apim-Subscription-Key":
                    PIXAZO_API_KEY
                },
                timeout=60,
            )

            status_response.raise_for_status()

            status_data = (
                status_response.json()
            )

        except requests.exceptions.RequestException as error:

            print(
                f"⚠️ Status check failed: {error}"
            )

            continue

        except ValueError as error:

            print(
                f"⚠️ Invalid status response: {error}"
            )

            continue

        status = status_data.get(
            "status"
        )

        print(
            f"⏳ Animation status "
            f"{poll_number}/{max_polls}: {status}"
        )

        # --------------------------------------------------
        # SUCCESS
        # --------------------------------------------------

        if status == "COMPLETED":

            output = status_data.get(
                "output",
                {}
            )

            media_urls = output.get(
                "media_url",
                []
            )

            if not media_urls:

                raise RuntimeError(
                    "Video completed but no media URL "
                    f"was returned: {status_data}"
                )

            video_url = media_urls[0]

            print()
            print(
                "✅ AI animation completed!"
            )

            print(
                "⬇️ Downloading video..."
            )

            try:

                video_response = requests.get(
                    video_url,
                    timeout=300,
                )

                video_response.raise_for_status()

            except requests.exceptions.RequestException as error:

                raise RuntimeError(
                    f"Failed to download generated video: "
                    f"{error}"
                ) from error

            if not video_response.content:

                raise RuntimeError(
                    "Downloaded video is empty."
                )

            with open(
                output_file,
                "wb"
            ) as video_file:

                video_file.write(
                    video_response.content
                )

            file_size = os.path.getsize(
                output_file
            )

            print(
                "🎉 Video saved:",
                output_file
            )

            print(
                "📦 File size:",
                file_size,
                "bytes"
            )

            print("=" * 60)

            return output_file

        # --------------------------------------------------
        # FAILURE
        # --------------------------------------------------

        elif status in [
            "FAILED",
            "ERROR"
        ]:

            error = status_data.get(
                "error",
                "Unknown error"
            )

            raise RuntimeError(
                "Pixazo AI video generation failed: "
                f"{error}"
            )

    raise RuntimeError(
        "Pixazo LTX animation timed out after "
        f"{max_polls * 5} seconds."
    )


def combine_videos(
    video_files,
    output_file
):
    """
    Combine multiple AI-generated vertical videos
    into one YouTube Short.
    """

    if not video_files:

        raise ValueError(
            "No video files provided."
        )

    print()
    print("=" * 60)
    print("🎬 COMBINING AI ANIMATED SCENES")
    print("=" * 60)

    # --------------------------------------------------
    # CHECK INPUT VIDEOS
    # --------------------------------------------------

    for video in video_files:

        if not os.path.exists(video):

            raise FileNotFoundError(
                f"Video not found: {video}"
            )

        print(
            f"🎞️ Adding: {video}"
        )

    # --------------------------------------------------
    # CREATE FFMPEG CONCAT FILE
    # --------------------------------------------------

    concat_file = "video_list.txt"

    with open(
        concat_file,
        "w",
        encoding="utf-8"
    ) as file:

        for video in video_files:

            absolute_path = (
                os.path.abspath(video)
            )

            # Escape single quotes for FFmpeg.
            escaped_path = (
                absolute_path
                .replace("'", "'\\''")
            )

            file.write(
                f"file '{escaped_path}'\n"
            )

    print()
    print("🔗 Joining videos...")

    command = [
        "ffmpeg",
        "-y",
        "-f",
        "concat",
        "-safe",
        "0",
        "-i",
        concat_file,
        "-c",
        "copy",
        output_file,
    ]

    result = subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    # --------------------------------------------------
    # REMOVE TEMPORARY FILE
    # --------------------------------------------------

    if os.path.exists(
        concat_file
    ):

        os.remove(
            concat_file
        )

    # --------------------------------------------------
    # CHECK FFMPEG RESULT
    # --------------------------------------------------

    if result.returncode != 0:

        print()
        print("❌ FFmpeg error:")
        print(result.stderr)

        raise RuntimeError(
            "Failed to combine videos."
        )

    if not os.path.exists(
        output_file
    ):

        raise RuntimeError(
            "Combined video was not created."
        )

    file_size = os.path.getsize(
        output_file
    )

    print()
    print(
        "✅ VIDEOS COMBINED SUCCESSFULLY"
    )

    print(
        f"🎬 Short video: {output_file}"
    )

    print(
        f"📦 File size: {file_size} bytes"
    )

    print("=" * 60)

    return output_file
