name: YouTube Kids Story Automation

on:
  workflow_dispatch:

  schedule:
    - cron: "30 15 * * *"

jobs:
  automation:
    runs-on: ubuntu-latest

    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Kids Story Automation
        run: python main.py
